version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres_db:5432/receipt_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receipt_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata: